name: Nightly

on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  nightly:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Create working branch
        run: |
          git branch -D npm-update || true
          git checkout -b npm-update
        env:
          CI: true

      - name: Update dependencies
        run: |
          npm ci
          npx npm-check-updates -u
          npm update
          npm install
        env:
          CI: true

      - name: Test
        run: npm run build
        env:
          CI: true

      ## FIX: https://github.com/github-actions-x/commit/issues/16
      ## https://github.com/rlespinasse/git-commit-data-action
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@1.3.0
      - name: Set git author
        run: git config user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" && git config user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
      ## /FIX

      - name: Commit generated files
        run: |
          git add package*.json || true
          git commit -m "Updated dependencies" || true

      - name: Check if changed from main
        run: |
          git diff --quiet HEAD main -- "package*.json" --exit-code || echo "CHANGED=true" >> $GITHUB_ENV
          echo Changed: ${{ env.CHANGED }}
        env:
          CI: true

      - name: Push generated files
        if: ${{ env.CHANGED == 'true' }}
        run: |
          git push --set-upstream origin npm-update --force
        env:
          CI: true

      - name: Open Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'npm-update'
          PULL_REQUEST_FROM_BRANCH: 'npm-update'
          PULL_REQUEST_BRANCH: 'main'

      - name: Find Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: npm-update

      - name: Merge Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: juliangruber/merge-pull-request-action@v1.1.0
        with:
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash
          github-token: ${{ secrets.GITHUB_TOKEN }}
