name: Test env vars

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  printInputs:
    runs-on: ubuntu-latest

    steps:
      - name: Set env var
        run: |
          echo "CHANGED=true" >> $GITHUB_ENV
        env:
          CI: true

      - name: Get env var
        run: |
          echo Changed: ${{ env.CHANGED }}
        env:
          CI: true
